-- MySQL Script generated by MySQL Workbench
-- sob, 26 lis 2016, 16:49:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relationship` (
  `idrelationship` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idrelationship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `born_in_idrelationship` INT NOT NULL,
  PRIMARY KEY (`idperson`, `born_in_idrelationship`),
  INDEX `fk_person_realtionship_idx` (`born_in_idrelationship` ASC),
  CONSTRAINT `fk_osoba_zwiazek1`
    FOREIGN KEY (`born_in_idrelationship`)
    REFERENCES `mydb`.`relationship` (`idrelationship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_has_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_has_relationship` (
  `person_idperson` INT NOT NULL,
  `relationship_idrelationship` INT NOT NULL,
  PRIMARY KEY (`person_idperson`, `relationship_idrelationship`),
  INDEX `fk_person_has_relationship_relationship_idx` (`relationship_idrelationship` ASC),
  INDEX `fk_person_has_relationship_person_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_osoba_has_zwiazek_osoba`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mydb`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_osoba_has_zwiazek_zwiazek1`
    FOREIGN KEY (`relationship_idrelationship`)
    REFERENCES `mydb`.`relationship` (`idrelationship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
